//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nekres.Music_Mixer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nekres.Music_Mixer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Music.
        /// </summary>
        internal static string Background_Music {
            get {
                return ResourceManager.GetString("Background Music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking link….
        /// </summary>
        internal static string Checking_link___ {
            get {
                return ResourceManager.GetString("Checking link...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        internal static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defeated.
        /// </summary>
        internal static string Defeated {
            get {
                return ResourceManager.GetString("Defeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable or disable this playlist..
        /// </summary>
        internal static string Enable_or_disable_this_playlist_ {
            get {
                return ResourceManager.GetString("Enable or disable this playlist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        internal static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Griffon.
        /// </summary>
        internal static string Griffon {
            get {
                return ResourceManager.GetString("Griffon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing default playlists..
        /// </summary>
        internal static string Importing_default_playlists_ {
            get {
                return ResourceManager.GetString("Importing default playlists.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jackal.
        /// </summary>
        internal static string Jackal {
            get {
                return ResourceManager.GetString("Jackal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link pasted. Checking….
        /// </summary>
        internal static string Link_pasted__Checking___ {
            get {
                return ResourceManager.GetString("Link pasted. Checking...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master Volume.
        /// </summary>
        internal static string Master_Volume {
            get {
                return ResourceManager.GetString("Master Volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mounted.
        /// </summary>
        internal static string Mounted {
            get {
                return ResourceManager.GetString("Mounted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mute when GW2 is in the background.
        /// </summary>
        internal static string Mute_when_GW2_is_in_the_background {
            get {
                return ResourceManager.GetString("Mute when GW2 is in the background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New database created..
        /// </summary>
        internal static string New_database_created_ {
            get {
                return ResourceManager.GetString("New database created.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string Night {
            get {
                return ResourceManager.GetString("Night", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output Device.
        /// </summary>
        internal static string Output_Device {
            get {
                return ResourceManager.GetString("Output Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Not Found..
        /// </summary>
        internal static string Page_Not_Found_ {
            get {
                return ResourceManager.GetString("Page Not Found.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste a video or audio link from your clipboard to add it to the playlist..
        /// </summary>
        internal static string Paste_a_video_or_audio_link_from_your_clipboard_to_add_it_to_the_playlist_ {
            get {
                return ResourceManager.GetString("Paste a video or audio link from your clipboard to add it to the playlist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste From Clipboard.
        /// </summary>
        internal static string Paste_From_Clipboard {
            get {
                return ResourceManager.GetString("Paste From Clipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Playlists.
        /// </summary>
        internal static string Playlists {
            get {
                return ResourceManager.GetString("Playlists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait..
        /// </summary>
        internal static string Please_wait_ {
            get {
                return ResourceManager.GetString("Please wait.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raptor.
        /// </summary>
        internal static string Raptor {
            get {
                return ResourceManager.GetString("Raptor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recommended platforms:.
        /// </summary>
        internal static string Recommended_platforms_ {
            get {
                return ResourceManager.GetString("Recommended platforms:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from Playlist.
        /// </summary>
        internal static string Remove_from_Playlist {
            get {
                return ResourceManager.GetString("Remove from Playlist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roller Beetle.
        /// </summary>
        internal static string Roller_Beetle {
            get {
                return ResourceManager.GetString("Roller Beetle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an output device….
        /// </summary>
        internal static string Select_an_output_device___ {
            get {
                return ResourceManager.GetString("Select an output device...", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Siege Turtle.
        /// </summary>
        internal static string Siege_Turtle {
            get {
                return ResourceManager.GetString("Siege Turtle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiff.
        /// </summary>
        internal static string Skiff {
            get {
                return ResourceManager.GetString("Skiff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skimmer.
        /// </summary>
        internal static string Skimmer {
            get {
                return ResourceManager.GetString("Skimmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skyscale.
        /// </summary>
        internal static string Skyscale {
            get {
                return ResourceManager.GetString("Skyscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong. Please try again..
        /// </summary>
        internal static string Something_went_wrong__Please_try_again_ {
            get {
                return ResourceManager.GetString("Something went wrong. Please try again.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Springer.
        /// </summary>
        internal static string Springer {
            get {
                return ResourceManager.GetString("Springer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This track is already in the playlist..
        /// </summary>
        internal static string This_track_is_already_in_the_playlist_ {
            get {
                return ResourceManager.GetString("This track is already in the playlist.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported website..
        /// </summary>
        internal static string Unsupported_website_ {
            get {
                return ResourceManager.GetString("Unsupported website.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a different Output Device.
        /// </summary>
        internal static string Use_a_different_Output_Device {
            get {
                return ResourceManager.GetString("Use a different Output Device", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warclaw.
        /// </summary>
        internal static string Warclaw {
            get {
                return ResourceManager.GetString("Warclaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your clipboard does not contain a valid link..
        /// </summary>
        internal static string Your_clipboard_does_not_contain_a_valid_link_ {
            get {
                return ResourceManager.GetString("Your clipboard does not contain a valid link.", resourceCulture);
            }
        }
    }
}
